os: linux
dist: bionic
sudo: false

language: cpp

addons:
  apt:
    packages:
      - clang-format

script:
  - cmake -S . -Bbuild
  - cmake --build build --target clangformat
  - diff --brief etalon/src src
  - diff --brief --exclude=CMakeLists.txt etalon/test test
  - cmake --build build
